### ISSUE TITLE
upgrading to 0.11.0 broken

### ISSUE THREAD

**Issue by kwon-young** [ridgeworks/clpBNR_pl#17]
Hello,
I just wanted to let you know that doing a `pack_install(clpBNR).` or `pack_upgrade(clpBNR).` in swi-prolog will upgrade clpBNR to the version `0.11.0` and fails to load with the following error:

``` prolog
?- use_module(library(clpBNR)).
ERROR: /home/kwon-young/.local/share/swi-prolog/pack/clpBNR/prolog/clpBNR.pl:29:
ERROR:    Domain error: `module_header' expected, found `:-print_message(error,history(expande
d("This version of clpBNR requires SWIP 9.1.5 or greater")))'
```

Since version 0.11.0 has no release on github, I suppose the fact that it is available on swi-prolog.org is an error.

**Comment by ridgeworks** [comment]
Version 0.11.0 requires SWIP 9.1.5 or greater for mathematically correct comparison, can you verify this is the case for your config?

That said, generating an error rather than a message, wasn't my intent, so I'll try and fix that.

**Comment by kwon-young** [comment]
Oh, that's right. I'm using SWIP 9.0.4 on fedora 38.
Previous version would generate a message so I assumed it was something else.
